// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:qjs/qjs.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<QJSABIArrayOrError Function(ffi.Pointer<QJSABIRuntime>, ffi.Size)>()
external QJSABIArrayOrError qjs_array_create(
  ffi.Pointer<QJSABIRuntime> rt,
  int length,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<QJSABIRuntime>, QJSABIArray)>()
external int qjs_array_get_length(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIArray arr,
);

@ffi.Native<
  QJSABIValueOrError Function(ffi.Pointer<QJSABIRuntime>, QJSABIArray, ffi.Size)
>()
external QJSABIValueOrError qjs_array_value_get_at_index(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIArray arr,
  int index,
);

@ffi.Native<
  QJSABIVoidOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIArray,
    ffi.Size,
    QJSABIValue,
  )
>()
external QJSABIVoidOrError qjs_array_value_set_at_index(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIArray arr,
  int index,
  QJSABIValue value,
);

@ffi.Native<
  QJSABIArrayBufferOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Void>,
    QJSABIMutableBufferRelease,
  )
>()
external QJSABIArrayBufferOrError qjs_arraybuffer_create_from_external_data(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Void> user_data,
  QJSABIMutableBufferRelease release_cb,
);

@ffi.Native<
  QJSABIUint8PtrOrError Function(ffi.Pointer<QJSABIRuntime>, QJSABIArrayBuffer)
>()
external QJSABIUint8PtrOrError qjs_arraybuffer_get_data(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIArrayBuffer ab,
);

@ffi.Native<
  QJSABISizeTOrError Function(ffi.Pointer<QJSABIRuntime>, QJSABIArrayBuffer)
>()
external QJSABISizeTOrError qjs_arraybuffer_get_size(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIArrayBuffer ab,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<QJSABIRuntime>, QJSABIBigInt)>()
external int qjs_bigint_as_int64(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIBigInt bi,
);

@ffi.Native<
  QJSABIBigIntOrError Function(ffi.Pointer<QJSABIRuntime>, ffi.Int64)
>()
external QJSABIBigIntOrError qjs_bigint_create_from_int64(
  ffi.Pointer<QJSABIRuntime> rt,
  int value,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<QJSABIRuntime>, QJSABIBigInt)>()
external bool qjs_bigint_is_int64(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIBigInt bi,
);

@ffi.Native<
  QJSABIStringOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<ffi.Char>,
  )
>()
external QJSABIStringOrError qjs_create_string_from_utf8(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<ffi.Char> str,
);

@ffi.Native<
  QJSABIValue Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
  )
>()
external QJSABIValue qjs_evaluate_javascript(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> script,
  int script_len,
  ffi.Pointer<ffi.Char> source_url,
);

@ffi.Native<
  QJSABIValue Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIFunction,
    QJSABIValue,
    ffi.Pointer<QJSABIValue>,
    ffi.Size,
  )
>()
external QJSABIValue qjs_function_call(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIFunction fn,
  QJSABIValue js_this,
  ffi.Pointer<QJSABIValue> args,
  int arg_count,
);

@ffi.Native<
  QJSABIValue Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIFunction,
    ffi.Pointer<QJSABIValue>,
    ffi.Size,
  )
>()
external QJSABIValue qjs_function_call_as_constructor(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIFunction fn,
  ffi.Pointer<QJSABIValue> args,
  int arg_count,
);

@ffi.Native<
  QJSABIFunctionOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIPropNameID,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Void>,
    QJSABIHostFunctionCall,
    QJSABIHostFunctionRelease,
  )
>()
external QJSABIFunctionOrError qjs_function_create_from_host(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIPropNameID name,
  int length,
  ffi.Pointer<ffi.Void> user_data,
  QJSABIHostFunctionCall call_cb,
  QJSABIHostFunctionRelease release_cb,
);

@ffi.Native<
  QJSABIBoolOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIObject,
    QJSABIFunction,
  )
>()
external QJSABIBoolOrError qjs_instance_of(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  QJSABIFunction ctor,
);

@ffi.Native<
  ffi.Pointer<QJSABIManagedPointer> Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<QJSABIManagedPointer>,
  )
>()
external ffi.Pointer<QJSABIManagedPointer> qjs_managed_pointer_clone(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<QJSABIManagedPointer> ptr,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<QJSABIManagedPointer>,
    ffi.Pointer<QJSABIManagedPointer>,
  )
>()
external bool qjs_managed_pointer_strict_equals(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<QJSABIManagedPointer> a,
  ffi.Pointer<QJSABIManagedPointer> b,
);

@ffi.Native<QJSABIObjectOrError Function(ffi.Pointer<QJSABIRuntime>)>()
external QJSABIObjectOrError qjs_object_create(
  ffi.Pointer<QJSABIRuntime> rt,
);

@ffi.Native<
  QJSABIObjectOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<ffi.Void>,
    QJSABIHostObjectGet,
    QJSABIHostObjectSet,
    QJSABIHostObjectGetOwnKeys,
    QJSABIHostObjectRelease,
  )
>()
external QJSABIObjectOrError qjs_object_create_from_host_object(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<ffi.Void> user_data,
  QJSABIHostObjectGet get_cb,
  QJSABIHostObjectSet set_cb,
  QJSABIHostObjectGetOwnKeys get_own_keys_cb,
  QJSABIHostObjectRelease release_cb,
);

@ffi.Native<
  QJSABIValueOrError Function(ffi.Pointer<QJSABIRuntime>, ffi.Uint64)
>()
external QJSABIValueOrError qjs_object_from_id(
  ffi.Pointer<QJSABIRuntime> rt,
  int id,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<QJSABIRuntime>, QJSABIObject)
>()
external ffi.Pointer<ffi.Void> qjs_object_get_native_state_data(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
);

@ffi.Native<
  QJSABIValue Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIObject,
    QJSABIPropNameID,
  )
>()
external QJSABIValue qjs_object_get_property_from_propnameid(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  QJSABIPropNameID name,
);

@ffi.Native<
  QJSABIValue Function(ffi.Pointer<QJSABIRuntime>, QJSABIObject, QJSABIValue)
>()
external QJSABIValue qjs_object_get_property_from_value(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  QJSABIValue key,
);

@ffi.Native<
  QJSABIArrayOrError Function(ffi.Pointer<QJSABIRuntime>, QJSABIObject)
>()
external QJSABIArrayOrError qjs_object_get_property_names(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
);

@ffi.Native<
  QJSABIBoolOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIObject,
    QJSABIPropNameID,
  )
>()
external QJSABIBoolOrError qjs_object_has_property_from_propnameid(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  QJSABIPropNameID name,
);

@ffi.Native<
  QJSABIBoolOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIObject,
    QJSABIValue,
  )
>()
external QJSABIBoolOrError qjs_object_has_property_from_value(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  QJSABIValue key,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<QJSABIRuntime>, QJSABIObject)>()
external bool qjs_object_is_array(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<QJSABIRuntime>, QJSABIObject)>()
external bool qjs_object_is_arraybuffer(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<QJSABIRuntime>, QJSABIObject)>()
external bool qjs_object_is_function(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
);

@ffi.Native<
  QJSABIVoidOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIObject,
    ffi.Pointer<ffi.Void>,
    QJSABINativeStateRelease,
  )
>()
external QJSABIVoidOrError qjs_object_set_native_state(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  ffi.Pointer<ffi.Void> user_data,
  QJSABINativeStateRelease release_cb,
);

@ffi.Native<
  QJSABIVoidOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIObject,
    QJSABIPropNameID,
    QJSABIValue,
  )
>()
external QJSABIVoidOrError qjs_object_set_property_from_propnameid(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  QJSABIPropNameID name,
  QJSABIValue value,
);

@ffi.Native<
  QJSABIVoidOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIObject,
    QJSABIValue,
    QJSABIValue,
  )
>()
external QJSABIVoidOrError qjs_object_set_property_from_value(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIObject obj,
  QJSABIValue key,
  QJSABIValue value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<QJSABIManagedPointer>)>()
external void qjs_pointer_release(
  ffi.Pointer<QJSABIManagedPointer> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<QJSABIManagedPointer>)>()
external void qjs_pointer_release_safe(
  ffi.Pointer<QJSABIManagedPointer> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<QJSABIPreparedJavaScript>)>()
external void qjs_preparedjavascript_release(
  ffi.Pointer<QJSABIPreparedJavaScript> prepared,
);

@ffi.Native<
  QJSABIPropNameID Function(ffi.Pointer<QJSABIRuntime>, QJSABIPropNameID)
>()
external QJSABIPropNameID qjs_propnameid_clone(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIPropNameID name,
);

@ffi.Native<
  QJSABIPropNameIDOrError Function(ffi.Pointer<QJSABIRuntime>, QJSABIString)
>()
external QJSABIPropNameIDOrError qjs_propnameid_create_from_string(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIString str,
);

@ffi.Native<
  QJSABIPropNameIDOrError Function(ffi.Pointer<QJSABIRuntime>, QJSABISymbol)
>()
external QJSABIPropNameIDOrError qjs_propnameid_create_from_symbol(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABISymbol sym,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<QJSABIRuntime>,
    QJSABIPropNameID,
    QJSABIPropNameID,
  )
>()
external bool qjs_propnameid_equals(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIPropNameID a,
  QJSABIPropNameID b,
);

@ffi.Native<
  QJSABIStringData Function(ffi.Pointer<QJSABIRuntime>, QJSABIPropNameID)
>()
external QJSABIStringData qjs_propnameid_get_data(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIPropNameID prop,
);

@ffi.Native<
  ffi.Pointer<QJSABIPropNameIDList> Function(
    ffi.Pointer<QJSABIPropNameID>,
    ffi.Size,
  )
>()
external ffi.Pointer<QJSABIPropNameIDList> qjs_propnameid_list_create(
  ffi.Pointer<QJSABIPropNameID> props,
  int size,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<QJSABIRuntime>, QJSABIPropNameID)
>()
external ffi.Pointer<ffi.Char> qjs_propnameid_to_utf8(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIPropNameID name,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<QJSABIManagedPointer>,
  )
>()
external void qjs_register_pointer(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<QJSABIManagedPointer> ptr,
);

@ffi.Native<ffi.Pointer<QJSABIRuntime> Function(QJSABIRuntimeConfig)>()
external ffi.Pointer<QJSABIRuntime> qjs_runtime_create(
  QJSABIRuntimeConfig config,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<QJSABIRuntime>, ffi.Int)>()
external bool qjs_runtime_drain_microtasks(
  ffi.Pointer<QJSABIRuntime> rt,
  int max_microtasks_hint,
);

@ffi.Native<QJSABIValue Function(ffi.Pointer<QJSABIRuntime>)>()
external QJSABIValue qjs_runtime_get_and_clear_js_error_value(
  ffi.Pointer<QJSABIRuntime> rt,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<QJSABIRuntime>)>()
external ffi.Pointer<ffi.Char>
qjs_runtime_get_and_clear_native_exception_message(
  ffi.Pointer<QJSABIRuntime> rt,
);

@ffi.Native<QJSABIObject Function(ffi.Pointer<QJSABIRuntime>)>()
external QJSABIObject qjs_runtime_get_global_object(
  ffi.Pointer<QJSABIRuntime> rt,
);

@ffi.Native<
  QJSABIPreparedJavaScriptOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
  )
>()
external QJSABIPreparedJavaScriptOrError qjs_runtime_prepared_javascript_create(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> utf8_source,
  int source_length,
  ffi.Pointer<ffi.Char> source_url,
);

@ffi.Native<
  QJSABIValueOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<QJSABIPreparedJavaScript>,
  )
>()
external QJSABIValueOrError qjs_runtime_prepared_javascript_evaluate(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<QJSABIPreparedJavaScript> prepared,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<QJSABIRuntime>)>()
external void qjs_runtime_release(
  ffi.Pointer<QJSABIRuntime> rt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<QJSABIRuntime>)>()
external void qjs_runtime_release_from_finalizer(
  ffi.Pointer<QJSABIRuntime> rt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<QJSABIRuntime>, QJSABIValue)>()
external void qjs_runtime_set_js_error_value(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIValue error_value,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<QJSABIRuntime>, ffi.Pointer<ffi.Char>)
>()
external void qjs_runtime_set_native_exception_message(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<ffi.Char> message,
);

@ffi.Native<
  QJSABIStringData Function(ffi.Pointer<QJSABIRuntime>, QJSABIString)
>()
external QJSABIStringData qjs_string_get_data(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIString str,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<QJSABIRuntime>, QJSABIString)
>()
external ffi.Pointer<ffi.Char> qjs_string_to_utf8(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIString str,
);

@ffi.Native<
  QJSABIValueOrError Function(
    ffi.Pointer<QJSABIRuntime>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external QJSABIValueOrError qjs_value_create_from_json_utf8(
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<ffi.Uint8> json_bytes,
  int length,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<QJSABIRuntime>, QJSABIValue)>()
external int qjs_value_get_unique_id(
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIValue val,
);

final class QJSABIArray extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABIArray> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABIArray>()..ref.pointer = pointer;
}

final class QJSABIArrayBuffer extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABIArrayBuffer> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABIArrayBuffer>()..ref.pointer = pointer;
}

final class QJSABIArrayBufferOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIArrayBufferOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABIArrayBufferOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIArrayOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIArrayOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABIArrayOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIBigInt extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABIBigInt> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABIBigInt>()..ref.pointer = pointer;
}

final class QJSABIBigIntOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIBigIntOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABIBigIntOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIBoolOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int bool_or_error;

  static ffi.Pointer<QJSABIBoolOrError> $allocate(
    ffi.Allocator $allocator, {
    required int bool_or_error,
  }) => $allocator<QJSABIBoolOrError>()..ref.bool_or_error = bool_or_error;
}

enum QJSABIErrorCode {
  QJSABIErrorCodeNativeException(0),
  QJSABIErrorCodeJSError(1);

  final int value;
  const QJSABIErrorCode(this.value);

  static QJSABIErrorCode fromValue(int value) => switch (value) {
    0 => QJSABIErrorCodeNativeException,
    1 => QJSABIErrorCodeJSError,
    _ => throw ArgumentError('Unknown value for QJSABIErrorCode: $value'),
  };
}

final class QJSABIFunction extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABIFunction> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABIFunction>()..ref.pointer = pointer;
}

final class QJSABIFunctionOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIFunctionOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABIFunctionOrError>()..ref.ptr_or_error = ptr_or_error;
}

typedef QJSABIHostFunctionCall =
    ffi.Pointer<ffi.NativeFunction<QJSABIHostFunctionCallFunction>>;
typedef QJSABIHostFunctionCallFunction = QJSABIValueOrError Function(
  ffi.Pointer<ffi.Void> user_data,
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<QJSABIValue> this_arg,
  ffi.Pointer<QJSABIValue> args,
  ffi.Size arg_count,
);
typedef DartQJSABIHostFunctionCallFunction = QJSABIValueOrError Function(
  ffi.Pointer<ffi.Void> user_data,
  ffi.Pointer<QJSABIRuntime> rt,
  ffi.Pointer<QJSABIValue> this_arg,
  ffi.Pointer<QJSABIValue> args,
  int arg_count,
);
typedef QJSABIHostFunctionRelease =
    ffi.Pointer<ffi.NativeFunction<QJSABIHostFunctionReleaseFunction>>;
typedef QJSABIHostFunctionReleaseFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> user_data,
);
typedef DartQJSABIHostFunctionReleaseFunction = void Function(
  ffi.Pointer<ffi.Void> user_data,
);
typedef QJSABIHostObjectGet =
    ffi.Pointer<ffi.NativeFunction<QJSABIHostObjectGetFunction>>;
typedef QJSABIHostObjectGetFunction = QJSABIValueOrError Function(
  ffi.Pointer<ffi.Void> user_data,
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIPropNameID name,
);
typedef QJSABIHostObjectGetOwnKeys =
    ffi.Pointer<ffi.NativeFunction<QJSABIHostObjectGetOwnKeysFunction>>;
typedef QJSABIHostObjectGetOwnKeysFunction =
    QJSABIPropNameIDListPtrOrError Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<QJSABIRuntime> rt,
    );
typedef QJSABIHostObjectRelease =
    ffi.Pointer<ffi.NativeFunction<QJSABIHostObjectReleaseFunction>>;
typedef QJSABIHostObjectReleaseFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> user_data,
);
typedef DartQJSABIHostObjectReleaseFunction = void Function(
  ffi.Pointer<ffi.Void> user_data,
);
typedef QJSABIHostObjectSet =
    ffi.Pointer<ffi.NativeFunction<QJSABIHostObjectSetFunction>>;
typedef QJSABIHostObjectSetFunction = QJSABIVoidOrError Function(
  ffi.Pointer<ffi.Void> user_data,
  ffi.Pointer<QJSABIRuntime> rt,
  QJSABIPropNameID name,
  ffi.Pointer<QJSABIValue> value,
);

final class QJSABIManagedPointer extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointerVTable> vtable;

  static ffi.Pointer<QJSABIManagedPointer> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointerVTable> vtable,
  }) => $allocator<QJSABIManagedPointer>()..ref.vtable = vtable;
}

final class QJSABIManagedPointerVTable extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<QJSABIManagedPointer> self)
    >
  >
  invalidate;

  static ffi.Pointer<QJSABIManagedPointerVTable> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<QJSABIManagedPointer> self)
      >
    >
    invalidate,
  }) => $allocator<QJSABIManagedPointerVTable>()..ref.invalidate = invalidate;
}

typedef QJSABIMutableBufferRelease =
    ffi.Pointer<ffi.NativeFunction<QJSABIMutableBufferReleaseFunction>>;
typedef QJSABIMutableBufferReleaseFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> user_data,
);
typedef DartQJSABIMutableBufferReleaseFunction = void Function(
  ffi.Pointer<ffi.Void> user_data,
);
typedef QJSABINativeStateRelease =
    ffi.Pointer<ffi.NativeFunction<QJSABINativeStateReleaseFunction>>;
typedef QJSABINativeStateReleaseFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> user_data,
);
typedef DartQJSABINativeStateReleaseFunction = void Function(
  ffi.Pointer<ffi.Void> user_data,
);

final class QJSABIObject extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABIObject> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABIObject>()..ref.pointer = pointer;
}

final class QJSABIObjectOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIObjectOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABIObjectOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIPreparedJavaScript extends ffi.Opaque {}

final class QJSABIPreparedJavaScriptOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIPreparedJavaScriptOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) =>
      $allocator<QJSABIPreparedJavaScriptOrError>()
        ..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIPropNameID extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABIPropNameID> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABIPropNameID>()..ref.pointer = pointer;
}

final class QJSABIPropNameIDList extends ffi.Struct {
  external ffi.Pointer<QJSABIPropNameIDListVTable> vtable;

  external ffi.Pointer<QJSABIPropNameID> props;

  @ffi.Size()
  external int size;

  static ffi.Pointer<QJSABIPropNameIDList> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIPropNameIDListVTable> vtable,
    required ffi.Pointer<QJSABIPropNameID> props,
    required int size,
  }) => $allocator<QJSABIPropNameIDList>()
    ..ref.vtable = vtable
    ..ref.props = props
    ..ref.size = size;
}

final class QJSABIPropNameIDListPtrOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIPropNameIDListPtrOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) =>
      $allocator<QJSABIPropNameIDListPtrOrError>()
        ..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIPropNameIDListVTable extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<QJSABIPropNameIDList>)>
  >
  release;

  static ffi.Pointer<QJSABIPropNameIDListVTable> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<QJSABIPropNameIDList>)>
    >
    release,
  }) => $allocator<QJSABIPropNameIDListVTable>()..ref.release = release;
}

final class QJSABIPropNameIDOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIPropNameIDOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABIPropNameIDOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIRuntime extends ffi.Opaque {}

final class QJSABIRuntimeConfig extends ffi.Struct {
  @ffi.Bool()
  external bool enable_eval;

  @ffi.Bool()
  external bool es6_proxy;

  @ffi.Bool()
  external bool microtask_queue;

  @ffi.Size()
  external int memory_limit;

  @ffi.Size()
  external int max_stack_size;

  @ffi.Size()
  external int gc_threshold;

  static ffi.Pointer<QJSABIRuntimeConfig> $allocate(
    ffi.Allocator $allocator, {
    required bool enable_eval,
    required bool es6_proxy,
    required bool microtask_queue,
    required int memory_limit,
    required int max_stack_size,
    required int gc_threshold,
  }) => $allocator<QJSABIRuntimeConfig>()
    ..ref.enable_eval = enable_eval
    ..ref.es6_proxy = es6_proxy
    ..ref.microtask_queue = microtask_queue
    ..ref.memory_limit = memory_limit
    ..ref.max_stack_size = max_stack_size
    ..ref.gc_threshold = gc_threshold;
}

final class QJSABISizeTOrError extends ffi.Struct {
  @ffi.Bool()
  external bool is_error;

  external UnnamedUnion$2 data;
}

final class QJSABIString extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABIString> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABIString>()..ref.pointer = pointer;
}

final class QJSABIStringData extends ffi.Struct {
  @ffi.Bool()
  external bool is_ascii;

  external ffi.Pointer<ffi.Void> data;

  @ffi.Size()
  external int length;

  static ffi.Pointer<QJSABIStringData> $allocate(
    ffi.Allocator $allocator, {
    required bool is_ascii,
    required ffi.Pointer<ffi.Void> data,
    required int length,
  }) => $allocator<QJSABIStringData>()
    ..ref.is_ascii = is_ascii
    ..ref.data = data
    ..ref.length = length;
}

final class QJSABIStringOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABIStringOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABIStringOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class QJSABISymbol extends ffi.Struct {
  external ffi.Pointer<QJSABIManagedPointer> pointer;

  static ffi.Pointer<QJSABISymbol> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<QJSABIManagedPointer> pointer,
  }) => $allocator<QJSABISymbol>()..ref.pointer = pointer;
}

final class QJSABISymbolOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int ptr_or_error;

  static ffi.Pointer<QJSABISymbolOrError> $allocate(
    ffi.Allocator $allocator, {
    required int ptr_or_error,
  }) => $allocator<QJSABISymbolOrError>()..ref.ptr_or_error = ptr_or_error;
}

final class QJSABIUint8PtrOrError extends ffi.Struct {
  @ffi.Bool()
  external bool is_error;

  external UnnamedUnion$1 data;
}

final class QJSABIValue extends ffi.Struct {
  @ffi.Int()
  external int kindAsInt;

  QJSABIValueKind get kind => QJSABIValueKind.fromValue(kindAsInt);
  set kind(QJSABIValueKind value) => kindAsInt = value.value;

  external UnnamedUnion data;
}

enum QJSABIValueKind {
  QJSABIValueKindUndefined(0),
  QJSABIValueKindNull(1),
  QJSABIValueKindBoolean(2),
  QJSABIValueKindError(3),
  QJSABIValueKindNumber(4),
  QJSABIValueKindSymbol(-2147483643),
  QJSABIValueKindBigInt(-2147483642),
  QJSABIValueKindString(-2147483641),
  QJSABIValueKindObject(-2147483639);

  final int value;
  const QJSABIValueKind(this.value);

  static QJSABIValueKind fromValue(int value) => switch (value) {
    0 => QJSABIValueKindUndefined,
    1 => QJSABIValueKindNull,
    2 => QJSABIValueKindBoolean,
    3 => QJSABIValueKindError,
    4 => QJSABIValueKindNumber,
    -2147483643 => QJSABIValueKindSymbol,
    -2147483642 => QJSABIValueKindBigInt,
    -2147483641 => QJSABIValueKindString,
    -2147483639 => QJSABIValueKindObject,
    _ => throw ArgumentError('Unknown value for QJSABIValueKind: $value'),
  };
}

final class QJSABIValueOrError extends ffi.Struct {
  external QJSABIValue value;
}

final class QJSABIVoidOrError extends ffi.Struct {
  @ffi.UintPtr()
  external int void_or_error;

  static ffi.Pointer<QJSABIVoidOrError> $allocate(
    ffi.Allocator $allocator, {
    required int void_or_error,
  }) => $allocator<QJSABIVoidOrError>()..ref.void_or_error = void_or_error;
}

const int QJS_ABI_POINTER_MASK = 2147483648;

final class UnnamedUnion extends ffi.Union {
  @ffi.Bool()
  external bool boolean;

  @ffi.Double()
  external double number;

  external ffi.Pointer<QJSABIManagedPointer> pointer;

  @ffi.UnsignedInt()
  external int errorAsInt;

  QJSABIErrorCode get error => QJSABIErrorCode.fromValue(errorAsInt);
  set error(QJSABIErrorCode value) => errorAsInt = value.value;
}

final class UnnamedUnion$1 extends ffi.Union {
  external ffi.Pointer<ffi.Uint8> val;

  @ffi.Uint16()
  external int error;
}

final class UnnamedUnion$2 extends ffi.Union {
  @ffi.Size()
  external int val;

  @ffi.Uint16()
  external int error;
}
